{% if gfortran_version is not defined %}
{% set gfortran_version = "7.5.0" %}
{% endif %}
{% set version = gfortran_version %}

{% if gfortran_version == "7.5.0" %}
{% set libgfortran_major_version = "4" %}
{% else %}
{% set libgfortran_major_version = "5" %}
{% endif %}

{% set version_suffix = "" %}
{% if gfortran_version == "11.0.0" %}
{% set version_suffix = ".dev0" %}
{% endif %}

package:
  name: gfortran_{{ cross_target_platform }}
  version: {{ version }}{{ version_suffix }}

build:
  number: 11
  skip: True  # [win]
  skip: True  # [gfortran_version == "11.0.0" and cross_target_platform != "osx-arm64"]
  skip: True  # [gfortran_version != "11.0.0" and (cross_target_platform == "osx-arm64" or target_platform == "osx-arm64")]
  run_exports:
    strong:
      - libgfortran {{ libgfortran_major_version }}.*
      - libgfortran{{ libgfortran_major_version }} >={{ version }}{{ version_suffix }}

requirements:
  host:
    - gfortran_impl_{{ cross_target_platform }} =={{ version }}{{ version_suffix }}
    - gfortran_impl_{{ target_platform }}
  run:
    - clang
    - ld64_{{ cross_target_platform }}
    - cctools_{{ cross_target_platform }}
    - gfortran_impl_{{ cross_target_platform }} =={{ version }}{{ version_suffix }}
    - gfortran_impl_{{ target_platform }}
    - libgfortran-devel_{{ cross_target_platform }} =={{ version }}{{ version_suffix }}
    - libgfortran {{ libgfortran_major_version }}.*                                   # [target_platform == cross_target_platform]
    - libgfortran{{ libgfortran_major_version }} >={{ version }}{{ version_suffix }}  # [target_platform == cross_target_platform]
    - clang_{{ cross_target_platform }}

test:
  files:
    - hello.f90
    - maths.f90
  commands:
    - echo {{ MACOSX_DEPLOYMENT_TARGET }}
    - gfortran --help
    - test "$(readlink $PREFIX/lib/gcc/{{ macos_machine }}/{{ version }}/clang)" = "../../../../bin/clang"

about:
  home: http://gcc.gnu.org/
  license: GPL-3.0-or-later WITH GCC-exception-3.1
  license_file: COPYING3
  summary: Fortran compiler from the GNU Compiler Collection

extra:
  recipe-maintainers:
    - beckermr
    - isuruf
