{% if gfortran_version == "7.5.0" %}
{% set libgfortran_major_version = "4" %}
{% else %}
{% set libgfortran_major_version = "5" %}
{% endif %}

package:
  name: gfortran_osx-64
  version: {{ gfortran_version }}

build:
  number: 6
  skip: True  # [win]
  run_exports:
    strong:
      - libgfortran {{ libgfortran_major_version }}.*
      - libgfortran{{ libgfortran_major_version }} >={{ gfortran_version }}

requirements:
  host:
    - clang
    - ld64_osx-64
    - cctools_osx-64
    - gfortran_impl_osx-64 =={{ version }}
  run:
    - clang
    - ld64_osx-64
    - cctools_osx-64
    - gfortran_impl_osx-64 =={{ version }}
    - libgfortran {{ libgfortran_major_version }}.*                                     # [osx]
    - libgfortran{{ libgfortran_major_version }} >={{ gfortran_version }}  # [osx]
    - clang_osx-64

test:
  files:
    - hello.f90
    - maths.f90
  commands:
    - echo {{ MACOSX_DEPLOYMENT_TARGET }}
    - gfortran --help
    - test "$(readlink $PREFIX/lib/gcc/{{ macos_machine }}/{{ version }}/clang)" = "../../../../bin/clang"

about:
  home: http://gcc.gnu.org/
  license: GPL-3.0-or-later WITH GCC-exception-3.1
  license_file: COPYING3
  summary: Fortran compiler from the GNU Compiler Collection

extra:
  recipe-maintainers:
    - beckermr
    - isuruf
