travis:
  secure:
    BINSTAR_TOKEN: VEAY1l0y18xqkmRbPawAYedd4wYyxZCnzYykP1C+uFxj0YZcTceFJvQmPpQWSbhvGJi1PlHcJg2G6sHaZVOI0fF8nvsMIWkFDS/31KCPavZdu3vVGH+EsbqEUBJ9hw4a/jJhzq0+kcpbLVI8gHaRNoj3Nea8Urr0lmKaj7TNUh2rwqI24l6EUrhL8fE88v60xr3anbGp4ifgrUFHkBKPWMFGXkvDkozT0WiykBQAoq0IOZ4xM6t1xrhLkdwk8X+tdYT4f0hQRe4/whqVL/Bjbagtv6SMOsM3JowtvCc24lLHxxDV2GAG9/QfGzyJ9yb8wY/uc2cxMHsIfX7j/tWXmN6LTV62BRpFeifCo/mRJ6++yhnEcqvxswdtjTrZuaEo5coGzHjIL2Y2PMic07HOhylfJ9MzAZkarmcxpQO3IgsS9hmsfwqTA7dAfI0CHfjUsuUklZyD440Y2Od4qg9/1Vckt0b5figED8YuyzeEbkFJ6IOgEWjwnlo+ThklY5+CAdSyH76sPdoVrrJmbvQ6okiULXwX6kLoMrPEPETUJqAG+C9hYA6xf8sjo3l1dEjnMqblvFnyWKbR+4e/hJWZzGllpWjNPFeKK9UChp18MhKbMEYvnz+5NhlqAncVLO57jNdHxOyjuGW6h9TdeHB8RAhzz22140jac/iOUHT9yrE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
